per_page: 10
accept_request: 2
books:
  page: 10
  size: "200x250"
  url: "/assets/a4.jpg"

admin:
  books:
    page: 10
    size: "150x150"
    url: "/assets/dac-nhan-tam.jpg"
    pic_size: 5
  detail_width: "100%"
  users:
    size: "70x70"
    url: "assets/avata.jpg"
users:
  size: "50x50"
  url: "/assets/user_3.png"
  pic_size: 5
reviews:
  page: 5
